%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook:
%    E:\Cloud\Dropbox\Materials2Simulation2Application\countRateLayer.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2015/06/29 11185:30:25

close all
clear all
clc

cg = 5;


rS0Mass = 4*pi*(cg*0.005/2)^3/3;
rS1Mass = 4*pi*(cg*0.006/2)^3/3;
rS2Mass = 4*pi*(cg*0.010/2)^3/3;
rS3Mass = 4*pi*(cg*0.016/2)^3/3;
rS4Mass = 4*pi*(cg*0.025/2)^3/3;
rS5Mass = 4*pi*(cg*0.040/2)^3/3;
rS6Mass = 4*pi*(cg*0.050/2)^3/3;

%% Import the data
[~, ~, raw] = xlsread('E:\Cloud\Dropbox\Materials2Simulation2Application\countRateLayer.xlsx','Sheet1','A2:W2109');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,2);
raw = raw(:,[1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
asimulatedTime = data(:,1);
asimulatedTime = asimulatedTime - asimulatedTime(1185);
step1 = cellVectors(:,1);


rS6percLay8 = data(:,8);
rS5percLay8 = data(:,7) - rS6percLay8;
rS4percLay8 = data(:,6) - (rS5percLay8 + rS6percLay8) ;
rS3percLay8 = data(:,5) - (rS4percLay8 + rS5percLay8 + rS6percLay8) ;
rS2percLay8 = data(:,4) - (rS3percLay8 + rS4percLay8 + rS5percLay8 + rS6percLay8) ;
rS1percLay8 = data(:,3) - (rS2percLay8 + rS3percLay8 + rS4percLay8 + rS5percLay8 + rS6percLay8) ;
rS0percLay8 = data(:,2) - (rS1percLay8 + rS2percLay8 + rS3percLay8 + rS4percLay8 + rS5percLay8 + rS6percLay8) ;

rS6percLay7 = data(:,15);
rS5percLay7 = data(:,14) - rS6percLay7;
rS4percLay7 = data(:,13) - (rS5percLay7 + rS6percLay7) ;
rS3percLay7 = data(:,12) - (rS4percLay7 + rS5percLay7 + rS6percLay7) ;
rS2percLay7 = data(:,11) - (rS3percLay7 + rS4percLay7 + rS5percLay7 + rS6percLay7) ;
rS1percLay7 = data(:,10) - (rS2percLay7 + rS3percLay7 + rS4percLay7 + rS5percLay7 + rS6percLay7) ;
rS0percLay7 = data(:,9) - (rS1percLay7 + rS2percLay7 + rS3percLay7 + rS4percLay7 + rS5percLay7 + rS6percLay7) ;

rS6percLay6 = data(:,22);
rS5percLay6 = data(:,21) - rS6percLay6;
rS4percLay6 = data(:,20) - (rS5percLay6 + rS6percLay6) ;
rS3percLay6 = data(:,19) - (rS4percLay6 + rS5percLay6 + rS6percLay6) ;
rS2percLay6 = data(:,18) - (rS3percLay6 + rS4percLay6 + rS5percLay6 + rS6percLay6) ;
rS1percLay6 = data(:,17) - (rS2percLay6 + rS3percLay6 + rS4percLay6 + rS5percLay6 + rS6percLay6) ;
rS0percLay6 = data(:,16) - (rS1percLay6 + rS2percLay6 + rS3percLay6 + rS4percLay6 + rS5percLay6 + rS6percLay6) ;

%%
rS6percLay8 = data(:,8)*rS6Mass;
rS5percLay8 = data(:,7)*rS5Mass;
rS4percLay8 = data(:,6)*rS4Mass;
rS3percLay8 = data(:,5)*rS3Mass;
rS2percLay8 = data(:,4)*rS2Mass;
rS1percLay8 = data(:,3)*rS1Mass;
rS0percLay8 = data(:,2)*rS0Mass;

rS6percLay7 = data(:,15)*rS6Mass;
rS5percLay7 = data(:,14)*rS5Mass;
rS4percLay7 = data(:,13)*rS4Mass;
rS3percLay7 = data(:,12)*rS3Mass;
rS2percLay7 = data(:,11)*rS2Mass;
rS1percLay7 = data(:,10)*rS1Mass;
rS0percLay7 = data(:,9)*rS0Mass;

rS6percLay6 = data(:,22)*rS6Mass;
rS5percLay6 = data(:,21)*rS5Mass;
rS4percLay6 = data(:,20)*rS4Mass;
rS3percLay6 = data(:,19)*rS3Mass;
rS2percLay6 = data(:,18)*rS2Mass;
rS1percLay6 = data(:,17)*rS1Mass;
rS0percLay6 = data(:,16)*rS0Mass;

%%
rS8totalVolume = rS6percLay8 + rS5percLay8 + rS4percLay8 + rS3percLay8 + rS2percLay8 + rS1percLay8 + rS0percLay8;
rS7totalVolume = rS6percLay7 + rS5percLay7 + rS4percLay7 + rS3percLay7 + rS2percLay7 + rS1percLay7 + rS0percLay7;



%% Clear temporary variables
clearvars data raw cellVectors;

%% Plot
% figure(1)
%  plot(asimulatedTime,rS0percLay6,'DisplayName','rS0percLay6');
%  hold all;
%  plot(asimulatedTime,rS1percLay6,'DisplayName','rS1percLay6');
%  plot(asimulatedTime,rS2percLay6,'DisplayName','rS2percLay6');
%  plot(asimulatedTime,rS3percLay6,'DisplayName','rS3percLay6');
%  plot(asimulatedTime,rS4percLay6,'DisplayName','rS4percLay6');
%  plot(asimulatedTime,rS5percLay6,'DisplayName','rS5percLay6');
%  plot(asimulatedTime,rS6percLay6,'DisplayName','rS6percLay6');
%  hold off;
%  
%  figure(2)
%  plot(asimulatedTime,rS0percLay8,'DisplayName','rS0percLay8');
%  hold all;
%  plot(asimulatedTime,rS1percLay8,'DisplayName','rS1percLay8');
%  plot(asimulatedTime,rS2percLay8,'DisplayName','rS2percLay8');
%  plot(asimulatedTime,rS3percLay8,'DisplayName','rS3percLay8');
%  plot(asimulatedTime,rS4percLay8,'DisplayName','rS4percLay8');
%  plot(asimulatedTime,rS5percLay8,'DisplayName','rS5percLay8');
%  plot(asimulatedTime,rS6percLay8,'DisplayName','rS6percLay8');
%  hold off;
%  
%  figure(3)
%  plot(asimulatedTime,rS0percLay7,'DisplayName','rS0percLay7');
%  hold all;
%  plot(asimulatedTime,rS1percLay7,'DisplayName','rS1percLay7');
%  plot(asimulatedTime,rS2percLay7,'DisplayName','rS2percLay7');
%  plot(asimulatedTime,rS3percLay7,'DisplayName','rS3percLay7');
%  plot(asimulatedTime,rS4percLay7,'DisplayName','rS4percLay7');
%  plot(asimulatedTime,rS5percLay7,'DisplayName','rS5percLay7');
%  plot(asimulatedTime,rS6percLay7,'DisplayName','rS6percLay7');
%  hold off;
 
 
  figure(4)
 h01 = plot(asimulatedTime(1185:1215),rS0percLay8(1185:1215),'b','LineWidth',2,'DisplayName','r =  2.5 mm, bottom layer');
 hold all;
  h02 = plot(asimulatedTime(1185:1215),rS1percLay8(1185:1215),'m','LineWidth',2,'DisplayName','r =  3.0 mm, bottom layer');
  h03 = plot(asimulatedTime(1185:1215),rS2percLay8(1185:1215),'g','LineWidth',2,'DisplayName','r =  5.0 mm, bottom layer');
  h04 = plot(asimulatedTime(1185:1215),rS3percLay8(1185:1215),'r','LineWidth',2,'DisplayName','r =  8.0 mm, bottom layer');
  h05 = plot(asimulatedTime(1185:1215),rS4percLay8(1185:1215),'c','LineWidth',2,'DisplayName','r = 12.5 mm, bottom layer');
  h06 = plot(asimulatedTime(1185:1215),rS5percLay8(1185:1215),'y','LineWidth',2,'DisplayName','r = 20.0 mm, bottom layer');
  h07 = plot(asimulatedTime(1185:1215),rS6percLay8(1185:1215),'k','LineWidth',2,'DisplayName','r = 25.0 mm, bottom layer');

  h08 = plot(asimulatedTime(1185:1215),rS0percLay7(1185:1215),'b','LineWidth',2,'DisplayName','r =  2.5 mm, central layer');
  h09 = plot(asimulatedTime(1185:1215),rS1percLay7(1185:1215),'m','LineWidth',2,'DisplayName','r =  3.0 mm, central layer');
  h10 = plot(asimulatedTime(1185:1215),rS2percLay7(1185:1215),'g','LineWidth',2,'DisplayName','r =  5.0 mm, central layer');
%  plot(asimulatedTime(1185:1215),rS3percLay7(1185:1215),'r','DisplayName','rS3percLay7');
%  plot(asimulatedTime(1185:1215),rS4percLay7(1185:1215),'c','DisplayName','rS4percLay7');
%  plot(asimulatedTime(1185:1215),rS5percLay7(1185:1215),'y','DisplayName','rS5percLay7');
%  plot(asimulatedTime(1185:1215),rS6percLay7(1185:1215),'k','DisplayName','rS6percLay7');
 
   h11 = plot(asimulatedTime(1185:3:1215),rS0percLay8(1185:3:1215),'b*','markers',18,'DisplayName','r =  2.5 mm, bottom layer');

  h12 = plot(asimulatedTime(1185:3:1215),rS1percLay8(1185:3:1215),'m*','markers',18,'DisplayName','r =  3.0 mm, bottom layer');
  h13 = plot(asimulatedTime(1185:3:1215),rS2percLay8(1185:3:1215),'g*','markers',18,'DisplayName','r =  5.0 mm, bottom layer');
  h14 = plot(asimulatedTime(1185:3:1215),rS3percLay8(1185:3:1215),'r*','markers',18,'DisplayName','r =  8.0 mm, bottom layer');
  h15 = plot(asimulatedTime(1185:3:1215),rS4percLay8(1185:3:1215),'c*','markers',18,'DisplayName','r = 12.5 mm, bottom layer');
%  h16 = plot(asimulatedTime(1185:3:1215),rS5percLay8(1185:3:1215),'y*','DisplayName','r = 20.0 mm, bottom layer');
  h17 = plot(asimulatedTime(1185:3:1215),rS6percLay8(1185:3:1215),'k*','markers',18,'DisplayName','r = 25.0 mm, bottom layer');

  h18 = plot(asimulatedTime(1185:3:1215),rS0percLay7(1185:3:1215),'bo','markers',18,'DisplayName','r =  2.5 mm, central layer');

  h19 = plot(asimulatedTime(1185:3:1215),rS1percLay7(1185:3:1215),'mo','markers',18,'DisplayName','r =  3.0 mm, central layer');
  h20 = plot(asimulatedTime(1185:3:1215),rS2percLay7(1185:3:1215),'go','markers',18,'DisplayName','r =  5.0 mm, central layer');
%  plot(asimulatedTime(1185:3:1215),rS3percLay7(1185:3:1215),'ro','DisplayName','rS3percLay7');
%  plot(asimulatedTime(1185:3:1215),rS4percLay7(1185:3:1215),'co','DisplayName','rS4percLay7');
%  plot(asimulatedTime(1185:3:1215),rS5percLay7(1185:3:1215),'yo','DisplayName','rS5percLay7');
%  plot(asimulatedTime(1185:3:1215),rS6percLay7(1185:3:1215),'ko','DisplayName','rS6percLay7');
%legend('rS0percLay8', 'rS1percLay8', 'rS2percLay8', , , , , , , , , , ,)
legend([h11 h12 h13 h14 h15 h17 h18 h19 h20], 'Location', 'NorthWest');  %
xlabel('time (s)','FontSize',20)
ylabel('volume (m^3)','FontSize',20)
set(gca,'fontname','times new roman','FontSize',20)  % Set it to times
xlim([-0.01 0.31])
 hold off;
 
%   figure(5)
%  plot(asimulatedTime,rS8totalVolume,'DisplayName','rS0percLay8');
%  hold all;
%  plot(asimulatedTime,rS7totalVolume,'DisplayName','rS1percLay8');
%  hold off;