%% Import data from text file.
% Script for importing data from the following text file:
%
%    /mnt/scratchPFMDaten/Luca/20150703/sinterChuteJSPLdevelopSimpli/postMass/countRateLayer3.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/07/03 10:07:51

clear all
close all
clc

%% Initialize variables.
filename = '/mnt/scratchPFMDaten/Luca/20150703/sinterChuteJSPLdevelopSimpli/postMass/countRateLayer3.txt';
delimiter = ' ';

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,3,4,5,6,7,8,9,18,19,20,21,22,23,24,27,28,29,30,31,32,33]
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(thousandsRegExp, ',', 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end

%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [1,3,4,5,6,7,8,9,18,19,20,21,22,23,24,27,28,29,30,31,32,33]);
rawCellColumns = raw(:, [2,10,11,12,13,14,15,16,17,25,26,34,35,36,37,38,39,40]);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Allocate imported array to column variable names
asimulatedTime = cell2mat(rawNumericColumns(:, 1));
%step1 = rawCellColumns(:, 1);
rS0percLay8 = cell2mat(rawNumericColumns(:, 2));
rS1percLay8 = cell2mat(rawNumericColumns(:, 3));
rS2percLay8 = cell2mat(rawNumericColumns(:, 4));
rS3percLay8 = cell2mat(rawNumericColumns(:, 5));
rS4percLay8 = cell2mat(rawNumericColumns(:, 6));
rS5percLay8 = cell2mat(rawNumericColumns(:, 7));
rS6percLay8 = cell2mat(rawNumericColumns(:, 8));
% VarName10 = rawCellColumns(:, 2);
% VarName11 = rawCellColumns(:, 3);
% VarName12 = rawCellColumns(:, 4);
% VarName13 = rawCellColumns(:, 5);
% VarName14 = rawCellColumns(:, 6);
% VarName15 = rawCellColumns(:, 7);
% VarName16 = rawCellColumns(:, 8);
% VarName24 = rawCellColumns(:, 9);
rS0percLay7 = cell2mat(rawNumericColumns(:, 9));
rS1percLay7 = cell2mat(rawNumericColumns(:, 10));
rS2percLay7 = cell2mat(rawNumericColumns(:, 11));
rS3percLay7 = cell2mat(rawNumericColumns(:, 12));
rS4percLay7 = cell2mat(rawNumericColumns(:, 13));
rS5percLay7 = cell2mat(rawNumericColumns(:, 14));
rS6percLay7 = cell2mat(rawNumericColumns(:, 15)); %


% = rawCellColumns(:, 10);
%  = rawCellColumns(:, 11);
rS0percLay6  = cell2mat(rawNumericColumns(:, 16));
rS1percLay6 = cell2mat(rawNumericColumns(:, 17));
rS2percLay6 = cell2mat(rawNumericColumns(:, 18));
rS3percLay6 = cell2mat(rawNumericColumns(:, 19));
rS4percLay6 = cell2mat(rawNumericColumns(:, 20));
rS5percLay6 = cell2mat(rawNumericColumns(:, 21)); %VarName32
rS6percLay6 = cell2mat(rawNumericColumns(:, 22)); %VarName33
% VarName34 = rawCellColumns(:, 12);
% VarName35 = rawCellColumns(:, 13);
% VarName36 = rawCellColumns(:, 14);
% VarName37 = rawCellColumns(:, 15);
% VarName38 = rawCellColumns(:, 16);
% VarName39 = rawCellColumns(:, 17);
% VarName40 = rawCellColumns(:, 18);

%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans raw col numericData rawData row regexstr result numbers invalidThousandsSeparator thousandsRegExp me rawNumericColumns rawCellColumns R;

%%
cg = 5;


rS0Mass = 4*pi*(cg*0.005/2)^3/3;
rS1Mass = 4*pi*(cg*0.006/2)^3/3;
rS2Mass = 4*pi*(cg*0.010/2)^3/3;
rS3Mass = 4*pi*(cg*0.016/2)^3/3;
rS4Mass = 4*pi*(cg*0.025/2)^3/3;
rS5Mass = 4*pi*(cg*0.040/2)^3/3;
rS6Mass = 4*pi*(cg*0.050/2)^3/3;

%rS6percLay8 = data(:,8);
rS5percLay8 = rS5percLay8 - rS6percLay8;
rS4percLay8 = rS4percLay8 - (rS5percLay8 + rS6percLay8) ;
rS3percLay8 = rS3percLay8 - (rS4percLay8 + rS5percLay8 + rS6percLay8) ;
rS2percLay8 = rS2percLay8 - (rS3percLay8 + rS4percLay8 + rS5percLay8 + rS6percLay8) ;
rS1percLay8 = rS1percLay8 - (rS2percLay8 + rS3percLay8 + rS4percLay8 + rS5percLay8 + rS6percLay8) ;
rS0percLay8 = rS0percLay8 - (rS1percLay8 + rS2percLay8 + rS3percLay8 + rS4percLay8 + rS5percLay8 + rS6percLay8) ;

% rS6percLay7 = data(:,15);
rS5percLay7 = rS5percLay7 - rS6percLay7;
rS4percLay7 = rS4percLay7 - (rS5percLay7 + rS6percLay7) ;
rS3percLay7 = rS3percLay7 - (rS4percLay7 + rS5percLay7 + rS6percLay7) ;
rS2percLay7 = rS2percLay7 - (rS3percLay7 + rS4percLay7 + rS5percLay7 + rS6percLay7) ;
rS1percLay7 = rS1percLay7 - (rS2percLay7 + rS3percLay7 + rS4percLay7 + rS5percLay7 + rS6percLay7) ;
rS0percLay7 = rS0percLay7 - (rS1percLay7 + rS2percLay7 + rS3percLay7 + rS4percLay7 + rS5percLay7 + rS6percLay7) ;

% rS6percLay6 = data(:,22);
rS5percLay6 = rS5percLay6 - rS6percLay6;
rS4percLay6 = rS4percLay6 - (rS5percLay6 + rS6percLay6) ;
rS3percLay6 = rS3percLay6 - (rS4percLay6 + rS5percLay6 + rS6percLay6) ;
rS2percLay6 = rS2percLay6 - (rS3percLay6 + rS4percLay6 + rS5percLay6 + rS6percLay6) ;
rS1percLay6 = rS1percLay6 - (rS2percLay6 + rS3percLay6 + rS4percLay6 + rS5percLay6 + rS6percLay6) ;
rS0percLay6 = rS0percLay6 - (rS1percLay6 + rS2percLay6 + rS3percLay6 + rS4percLay6 + rS5percLay6 + rS6percLay6) ;

%%
rS6percLay8 = rS6percLay8 * rS6Mass;
rS5percLay8 = rS5percLay8 * rS5Mass;
rS4percLay8 = rS4percLay8 * rS4Mass;
rS3percLay8 = rS3percLay8 * rS3Mass;
rS2percLay8 = rS2percLay8 * rS2Mass;
rS1percLay8 = rS1percLay8 * rS1Mass;
rS0percLay8 = rS0percLay8 * rS0Mass;

rS6percLay7 = rS6percLay7 * rS6Mass;
rS5percLay7 = rS5percLay7 * rS5Mass;
rS4percLay7 = rS4percLay7 * rS4Mass;
rS3percLay7 = rS3percLay7 * rS3Mass;
rS2percLay7 = rS2percLay7 * rS2Mass;
rS1percLay7 = rS1percLay7 * rS1Mass;
rS0percLay7 = rS0percLay7 * rS0Mass;

rS6percLay6 = rS6percLay6 * rS6Mass;
rS5percLay6 = rS5percLay6 * rS5Mass;
rS4percLay6 = rS4percLay6 * rS4Mass;
rS3percLay6 = rS3percLay6 * rS3Mass;
rS2percLay6 = rS2percLay6 * rS2Mass;
rS1percLay6 = rS1percLay6 * rS1Mass;
rS0percLay6 = rS0percLay6 * rS0Mass;

%%
rS8totalVolume = rS6percLay8 + rS5percLay8 + rS4percLay8 + rS3percLay8 + rS2percLay8 + rS1percLay8 + rS0percLay8;
rS7totalVolume = rS6percLay7 + rS5percLay7 + rS4percLay7 + rS3percLay7 + rS2percLay7 + rS1percLay7 + rS0percLay7;



%% Clear temporary variables
clearvars data raw cellVectors;

%% Plot
figure(1)
plot(asimulatedTime,rS0percLay6,'DisplayName','rS0percLay6');
hold all;
plot(asimulatedTime,rS1percLay6,'DisplayName','rS1percLay6');
plot(asimulatedTime,rS2percLay6,'DisplayName','rS2percLay6');
plot(asimulatedTime,rS3percLay6,'DisplayName','rS3percLay6');
plot(asimulatedTime,rS4percLay6,'DisplayName','rS4percLay6');
plot(asimulatedTime,rS5percLay6,'DisplayName','rS5percLay6');
plot(asimulatedTime,rS6percLay6,'DisplayName','rS6percLay6');
hold off;

figure(2)
plot(asimulatedTime,rS0percLay8,'DisplayName','rS0percLay8');
hold all;
plot(asimulatedTime,rS1percLay8,'DisplayName','rS1percLay8');
plot(asimulatedTime,rS2percLay8,'DisplayName','rS2percLay8');
plot(asimulatedTime,rS3percLay8,'DisplayName','rS3percLay8');
plot(asimulatedTime,rS4percLay8,'DisplayName','rS4percLay8');
plot(asimulatedTime,rS5percLay8,'DisplayName','rS5percLay8');
plot(asimulatedTime,rS6percLay8,'DisplayName','rS6percLay8');
hold off;

figure(3)
plot(asimulatedTime,rS0percLay7,'DisplayName','rS0percLay7');
hold all;
plot(asimulatedTime,rS1percLay7,'DisplayName','rS1percLay7');
plot(asimulatedTime,rS2percLay7,'DisplayName','rS2percLay7');
plot(asimulatedTime,rS3percLay7,'DisplayName','rS3percLay7');
plot(asimulatedTime,rS4percLay7,'DisplayName','rS4percLay7');
plot(asimulatedTime,rS5percLay7,'DisplayName','rS5percLay7');
plot(asimulatedTime,rS6percLay7,'DisplayName','rS6percLay7');
hold off;


figure(4)
h01 = plot(asimulatedTime(1185:1215),rS0percLay8(1185:1215),'b','LineWidth',2,'DisplayName','r =  2.5 mm, bottom layer');
hold all;
h02 = plot(asimulatedTime(1185:1215),rS1percLay8(1185:1215),'m','LineWidth',2,'DisplayName','r =  3.0 mm, bottom layer');
h03 = plot(asimulatedTime(1185:1215),rS2percLay8(1185:1215),'g','LineWidth',2,'DisplayName','r =  5.0 mm, bottom layer');
h04 = plot(asimulatedTime(1185:1215),rS3percLay8(1185:1215),'r','LineWidth',2,'DisplayName','r =  8.0 mm, bottom layer');
h05 = plot(asimulatedTime(1185:1215),rS4percLay8(1185:1215),'c','LineWidth',2,'DisplayName','r = 12.5 mm, bottom layer');
h06 = plot(asimulatedTime(1185:1215),rS5percLay8(1185:1215),'y','LineWidth',2,'DisplayName','r = 20.0 mm, bottom layer');
h07 = plot(asimulatedTime(1185:1215),rS6percLay8(1185:1215),'k','LineWidth',2,'DisplayName','r = 25.0 mm, bottom layer');

h08 = plot(asimulatedTime(1185:1215),rS0percLay7(1185:1215),'b','LineWidth',2,'DisplayName','r =  2.5 mm, central layer');
h09 = plot(asimulatedTime(1185:1215),rS1percLay7(1185:1215),'m','LineWidth',2,'DisplayName','r =  3.0 mm, central layer');
h10 = plot(asimulatedTime(1185:1215),rS2percLay7(1185:1215),'g','LineWidth',2,'DisplayName','r =  5.0 mm, central layer');
%  plot(asimulatedTime(1185:1215),rS3percLay7(1185:1215),'r','DisplayName','rS3percLay7');
%  plot(asimulatedTime(1185:1215),rS4percLay7(1185:1215),'c','DisplayName','rS4percLay7');
%  plot(asimulatedTime(1185:1215),rS5percLay7(1185:1215),'y','DisplayName','rS5percLay7');
%  plot(asimulatedTime(1185:1215),rS6percLay7(1185:1215),'k','DisplayName','rS6percLay7');

h11 = plot(asimulatedTime(1185:3:1215),rS0percLay8(1185:3:1215),'b*','markers',18,'DisplayName','r =  2.5 mm, bottom layer');

h12 = plot(asimulatedTime(1185:3:1215),rS1percLay8(1185:3:1215),'m*','markers',18,'DisplayName','r =  3.0 mm, bottom layer');
h13 = plot(asimulatedTime(1185:3:1215),rS2percLay8(1185:3:1215),'g*','markers',18,'DisplayName','r =  5.0 mm, bottom layer');
h14 = plot(asimulatedTime(1185:3:1215),rS3percLay8(1185:3:1215),'r*','markers',18,'DisplayName','r =  8.0 mm, bottom layer');
h15 = plot(asimulatedTime(1185:3:1215),rS4percLay8(1185:3:1215),'c*','markers',18,'DisplayName','r = 12.5 mm, bottom layer');
%  h16 = plot(asimulatedTime(1185:3:1215),rS5percLay8(1185:3:1215),'y*','DisplayName','r = 20.0 mm, bottom layer');
h17 = plot(asimulatedTime(1185:3:1215),rS6percLay8(1185:3:1215),'k*','markers',18,'DisplayName','r = 25.0 mm, bottom layer');

h18 = plot(asimulatedTime(1185:3:1215),rS0percLay7(1185:3:1215),'bo','markers',18,'DisplayName','r =  2.5 mm, central layer');

h19 = plot(asimulatedTime(1185:3:1215),rS1percLay7(1185:3:1215),'mo','markers',18,'DisplayName','r =  3.0 mm, central layer');
h20 = plot(asimulatedTime(1185:3:1215),rS2percLay7(1185:3:1215),'go','markers',18,'DisplayName','r =  5.0 mm, central layer');
%  plot(asimulatedTime(1185:3:1215),rS3percLay7(1185:3:1215),'ro','DisplayName','rS3percLay7');
%  plot(asimulatedTime(1185:3:1215),rS4percLay7(1185:3:1215),'co','DisplayName','rS4percLay7');
%  plot(asimulatedTime(1185:3:1215),rS5percLay7(1185:3:1215),'yo','DisplayName','rS5percLay7');
%  plot(asimulatedTime(1185:3:1215),rS6percLay7(1185:3:1215),'ko','DisplayName','rS6percLay7');
%legend('rS0percLay8', 'rS1percLay8', 'rS2percLay8', , , , , , , , , , ,)
legend([h11 h12 h13 h14 h15 h17 h18 h19 h20], 'Location', 'NorthWest');  %
xlabel('time (s)','FontSize',20)
ylabel('volume (m^3)','FontSize',20)
set(gca,'fontname','times new roman','FontSize',20)  % Set it to times
xlim([-0.01 0.31])
hold off;

figure(5)
plot(asimulatedTime,rS8totalVolume,'DisplayName','rS0percLay8');
hold all;
plot(asimulatedTime,rS7totalVolume,'DisplayName','rS1percLay8');
hold off;

figure(6)
plot(asimulatedTime,rS6percLay6,'DisplayName','rS6percLay6');hold all;plot(asimulatedTime,rS6percLay7,'DisplayName','rS6percLay7');plot(asimulatedTime,rS6percLay8,'DisplayName','rS6percLay8');hold off;

figure(7)
plot(asimulatedTime,rS5percLay6,'DisplayName','rS5percLay6');hold all;plot(asimulatedTime,rS5percLay7,'DisplayName','rS5percLay7');plot(asimulatedTime,rS5percLay8,'DisplayName','rS5percLay8');hold off;


figure(8)
plot(asimulatedTime,rS4percLay6,'DisplayName','rS4percLay6');hold all;plot(asimulatedTime,rS4percLay7,'DisplayName','rS4percLay7');plot(asimulatedTime,rS4percLay8,'DisplayName','rS4percLay8');hold off;


figure(9)
plot(asimulatedTime,rS3percLay6,'DisplayName','rS3percLay6');hold all;plot(asimulatedTime,rS3percLay7,'DisplayName','rS3percLay7');plot(asimulatedTime,rS3percLay8,'DisplayName','rS3percLay8');hold off;


figure(10)
plot(asimulatedTime,rS2percLay6,'DisplayName','rS2percLay6');hold all;plot(asimulatedTime,rS2percLay7,'DisplayName','rS2percLay7');plot(asimulatedTime,rS2percLay8,'DisplayName','rS2percLay8');hold off;


figure(11)
plot(asimulatedTime,rS1percLay6,'DisplayName','rS1percLay6');hold all;plot(asimulatedTime,rS1percLay7,'DisplayName','rS1percLay7');plot(asimulatedTime,rS1percLay8,'DisplayName','rS1percLay8');hold off;


figure(12)
plot(asimulatedTime,rS0percLay6,'DisplayName','rS0percLay6');hold all;plot(asimulatedTime,rS0percLay7,'DisplayName','rS0percLay7');plot(asimulatedTime,rS0percLay8,'DisplayName','rS0percLay8');hold off;


